server:
  port: 9001

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  boot:
    admin:
      username: admin
      password: admin

security:
  user:
    name: admin
    password: admin